version: '3.5'

services:
   web:
     build:
       context: '.'
       args:
         uid: 1000
     volumes:
       - .:/var/www/html
     ports:
       - 8001:80
     environment:
       - APACHE_RUN_USER=#1000
       - APACHE_RUN_GROUP=#1000